### ISSUE TITLE
Option to run llvm-lines on particular example or test in the crate

### ISSUE THREAD

**Issue by bluss** [dtolnay/cargo-llvm-lines#16]
(Feature request) An option that would be equivalent to --example X or --test Y, and show the instantiations for that target.

**Comment by graydon** [comment]
Yes please! Currently doing somewhat contorted test-embedded-in-a-binary-of-a-subcrate business to accomplish this.

(Also this tool is extremely fantastic and sorely needed by the ecosystem, bravo for building it! You may not believe this but "count the IR" [is a thing I put in the compiler](https://github.com/rust-lang/rust/pull/7456) in an extremely primitive form a million years ago -- outputting du-compatible output so you could browse with xdu! -- and even in that form it was one of the most effective tools in the kit for figuring out crude "where to trim" in a rust program.)

**Comment by bluss** [comment]
--example is done in #42 :slightly_smiling_face:
