### ISSUE TITLE
"thin LTO buffers without LLVM's NameAnonGlobals pass"

### ISSUE THREAD

**Issue by SimonSapin** [dtolnay/cargo-llvm-lines#17]
When trying this tool on Servo’s `script` crate (which take a very long time to compile), I get this error:

```
error: The current compilation is going to use thin LTO buffers without running LLVM's NameAnonGlobals pass. This will likely cause errors in LLVM. Consider adding -C passes=name-anon-globals to the compiler command line.
error: aborting due to previous error
error: could not compile `script`.
To learn more, run the command again with --verbose.
Ran --emit=llvm-ir but did not find output IR
```

I don’t know what this means.

I’ve had to `cd` into the `component/script` directory of https://github.com/servo/servo because llvm-lines doesn’t seem to run in a Cargo workspace, and apply this patch (on top of revision `e1cc38bea8a701108b6f2fa809f341769613b55f`, but another one should be similar).

```diff
diff --git components/script/Cargo.toml components/script/Cargo.toml
index 9f98ff3090..4152e6f870 100644
--- components/script/Cargo.toml
+++ components/script/Cargo.toml
@@ -103,7 +103,7 @@ servo_rand = { path = "../rand" }
 servo_url = { path = "../url" }
 smallvec = { version = "0.6", features = ["std", "union"] }
 sparkle = "0.1"
-style = { path = "../style", features = ["servo"] }
+style = { path = "../style", features = ["servo", "servo-layout-2013"] }
 style_traits = { path = "../style_traits" }
 swapper = "0.1"
 tendril = { version = "0.4.1", features = ["encoding_rs"] }
```

This is because Servo contributors normally don’t run `cargo` directly, our `mach` tool has its own configuration and runs `cargo` with selected feature flags. (By the way, it would be semi-useful for non-trivial build systems to separate the "run `cargo rustc` with these options" from the rest of `llvm-lines`.)

**Comment by rfk** [comment]
FWIW, I got a similar error message when trying to run this on a crate from https://github.com/mozilla/application-services. Switching to nightly via rustup got things working for me.

**Comment by SimonSapin** [comment]
The above was with `nightly-2020-04-08`, a.k.a. `rustc 1.44.0-nightly (42abbd887 2020-04-07)`. Upgrading to today’s Nightly fixes the issue, thanks!
