### ISSUE TITLE
*Somehow* run across the whole workspace

### ISSUE THREAD

**Issue by matklad** [dtolnay/cargo-llvm-lines#25]
We've been using `cargo llvm-lines` with great success ([before](https://user-images.githubusercontent.com/308347/86206821-f093b080-bb75-11ea-815d-9973bee870cb.png), [after](https://user-images.githubusercontent.com/308347/86750968-02c69080-c047-11ea-8815-d75be281585d.png)) in rust-analyzer! 

One thing we've noticed is that the biggest win comes from noticing things that are monomorphised *in the wrong crate*. Basically, if you have a generic `fn<T> foo()` function in crate `A`, and use it in crates `B` and `C`, you compile it twice. At the moment, `cargo llvm-lines` surfaces this info only indirectly, as it works on a crate at a time. So, you can use it to pin-point this issue if you already suspect it might be there, but it's hard to use `cargo llvm-lines` to discover it in the first place.

It would be cool (but I totally see how this is a big ask, as `cargo llvm-lines` doesn't really work that way :-) ) to be able to apply `cargo llvm-lines` to the whole workspace, and see per-crate stats in the same output.

**Comment by matklad** [comment]
See also discussion in https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/profiling.20code.20usage

**Comment by panstromek** [comment]
Is this the equivalent of "just" running the tool in every dependency/workspace crate source folder and then merging the results? 

Or does something special happens when you compile the full dependency graph?

**Comment by matklad** [comment]
I've realised that this is already possible by enabling fat LTO:

```console
$ CARGO_PROFILE_RELEASE_LTO=fat cargo llvm-lines --release
```

**Comment by nnethercote** [comment]
Seems like a documentation fix is in order for this issue. @matklad, can you suggest a sentence or two for the use case you have in mind for the fat LTO command? I assume this is only relevant when you are using a workspace. Are there any other relevant constraints? Thank you :)
