### ISSUE TITLE
Unsuccessful `cargo rustc` invocation: The system cannot find the file specified. (os error 2)

### ISSUE THREAD

**Issue by smmalis37** [dtolnay/cargo-llvm-lines#26]
Tried to run `cargo llvm-lines` on [a project of mine](https://github.com/smmalis37/wasm-playground), got the above error message. Unfortunately it doesn't tell me which file, this is all I've got. After the error it does output some statistics, but it seems like they're only for functions from core and alloc, not any of my code or the other crates it depends on. Running on Win 10 x64. Version is 0.4.3.

<details><summary>Full output:</summary>

```
> cargo llvm-lines
   Compiling wasm-playground v0.1.0 (C:\Users\smmal\Desktop\code\wasm-playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
Unsuccessful `cargo rustc` invocation: The system cannot find the file specified. (os error 2)
  Lines       Copies     Function name
  -----       ------     -------------
  189 (100%)  11 (100%)  (TOTAL)
   51 (27.0%)  1 (9.1%)  core::alloc::global::GlobalAlloc::realloc
   32 (16.9%)  1 (9.1%)  core::alloc::global::GlobalAlloc::alloc_zeroed
   20 (10.6%)  1 (9.1%)  core::alloc::layout::Layout::from_size_align_unchecked
   19 (10.1%)  1 (9.1%)  __rg_realloc
   16 (8.5%)   1 (9.1%)  __rg_dealloc
   13 (6.9%)   1 (9.1%)  __rg_alloc
   13 (6.9%)   1 (9.1%)  __rg_alloc_zeroed
    8 (4.2%)   1 (9.1%)  core::alloc::layout::Layout::align
    7 (3.7%)   1 (9.1%)  core::num::NonZeroUsize::new_unchecked
    6 (3.2%)   1 (9.1%)  core::alloc::layout::Layout::size
    4 (2.1%)   1 (9.1%)  core::num::NonZeroUsize::get
```
</details>

**Comment by smmalis37** [comment]
Some quick tracing shows it's apparently looking for cat.exe, which of course doesn't exist on Windows. Is the dependency on cat for unix-like oses truly necessary?

Here you can see it searching through my entire PATH:

![image](https://user-images.githubusercontent.com/4054472/89380931-3bd93b80-d6ad-11ea-89ef-1d636ef02572.png)

**Comment by dtolnay** [comment]
I tried a fix in 0.4.4 but I don't have access to Windows to test. Could you confirm whether this is fixed after updating?

**Comment by smmalis37** [comment]
On 0.4.5 the error message has disappeared, but the other output is unchanged. Is that output correct, or is it missing things? Does this have something to do with the wasm-related macros in my project? Or is there a way to specify a compile target to see if some sort of conditional compilation is removing things?

**Comment by smmalis37** [comment]
I got access to a linux box and get the same output there, so I guess we're good.
