### ISSUE TITLE
0.4.7 broke support for passing extra arguments through llvm-lines

### ISSUE THREAD

**Issue by Mark-Simulacrum** [dtolnay/cargo-llvm-lines#39]
There's quite a bit of argument refactoring in the 0.4.6 to 0.4.7 diff, so I'm not sure of the precise commit, but previously `cargo llvm-lines -- -Zverbose` for example would've worked, passing the -Zverbose to rustc (like cargo rustc does). perf.rust-lang.org used this support.

I think this was likely unintentional -- perhaps we could re-add that support?

**Comment by dtolnay** [comment]
Sorry about the breakage. This was not intentional. Fixed in 0.4.9.
