### ISSUE TITLE
release 0.4.27 was not completed 

### ISSUE THREAD

**Issue by chenrui333** [dtolnay/cargo-llvm-lines#70]
👋 it looks like the 0.4.27 release was not completed in the sense of the release was not marked as `latest release` despite [the action run was completed successfully](https://github.com/dtolnay/cargo-llvm-lines/actions/runs/4791917107).

relates to https://github.com/Homebrew/homebrew-core/pull/129244

**Comment by dtolnay** [comment]
Fixed. Thank you for pointing it out.
